package br.com.ragah.view;

import br.com.ragah.dao.DAOFactory;
import br.com.ragah.dao.model.CidadeDAO;
import br.com.ragah.domain.Cidade;
import br.com.ragah.table.model.CidadeTableModel;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author douglas
 */
public class FrmBuscaCidade extends javax.swing.JDialog {

    private List<Cidade> listaCidades;

    public FrmBuscaCidade(Window parent, List<Cidade> cidades) {
        super(parent, DEFAULT_MODALITY_TYPE);
        initComponents();
        this.listaCidades = cidades;
        initialize();
    }

    public void atualizarTabela() {
        tbCidades.setModel(new CidadeTableModel(this.listaCidades));
//        tbCidades.setDefaultRenderer(Object.class, new CidadeCellRenderer());
        ((AbstractTableModel) tbCidades.getModel()).fireTableDataChanged();
    }

    private void initialize() {

        atualizarTabela();
        eventoFechar();

        // Se teclarmos ESC nesta janela, ela irá se fechar:  
        this.getRootPane().registerKeyboardAction((ActionEvent e) -> {
            FrmBuscaCidade.this.retornarCidade();
            FrmBuscaCidade.this.dispose();
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);

    }

    private void eventoFechar() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                retornarCidade();
            }
        });
    }

    private Boolean retornarCidade() {

        int row = this.tbCidades.getSelectedRow();

        if (row != (-1)) {

            CidadeTableModel cidadeTableModel = new CidadeTableModel(this.listaCidades);
            Cidade c = cidadeTableModel.get(row);            

            if (this.getParent() instanceof FrmRegistroFuncionario) {
                FrmRegistroFuncionario frmRegistroFuncionario = FrmRegistroFuncionario.getInstancia();
                System.out.println(frmRegistroFuncionario.toString());
                frmRegistroFuncionario.setCidade(c);
                this.dispose();
            }

            return true;
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btOk = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCidades = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busca de Materiais");

        btOk.setMnemonic('O');
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        tbCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCidades.setToolTipText("");
        tbCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCidadesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCidades);

        jLabel1.setText("Pesquisar:");

        tfPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btOk))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPesquisa)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(7, 7, 7)
                .addComponent(btOk)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if (!retornarCidade()) {
            this.dispose();
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void tbCidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCidadesMouseClicked
        if (evt.getClickCount() == 2) {
            retornarCidade();
        }
    }//GEN-LAST:event_tbCidadesMouseClicked

    private void tfPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaKeyReleased
        CidadeDAO cdao = DAOFactory.getDefaultDAOFactory().getCidadeDAO();
        listaCidades = cdao.buscarPorNome(tfPesquisa.getText());
        atualizarTabela();
    }//GEN-LAST:event_tfPesquisaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbCidades;
    private javax.swing.JTextField tfPesquisa;
    // End of variables declaration//GEN-END:variables
}
