package br.com.ragah.view;

import br.com.ragah.dao.DAOFactory;
import br.com.ragah.dao.model.UsuarioDAO;
import br.com.ragah.util.Sessao;
import br.com.ragah.domain.Usuario;
import br.com.ragah.util.Seguranca;
import java.awt.Color;
import java.awt.Window;
import javax.swing.JOptionPane;

/**
 *
 * @author douglas
 */
public class FrmMudaSenha extends javax.swing.JDialog {

    /**
     * Creates new form FrmMudaSenha
     *
     * @param parent
     */
    public FrmMudaSenha(Window parent) {
        super(parent, DEFAULT_MODALITY_TYPE);
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSenhaAtual = new javax.swing.JPasswordField();
        tfNovaSenha = new javax.swing.JPasswordField();
        tfConfirmacao = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        btSair = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbAlerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mudança de Senha");

        jLabel1.setText("Senha atual:");

        jLabel2.setText("Confirmação:");

        jLabel3.setText("Nova senha:");

        tfConfirmacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfConfirmacaoKeyReleased(evt);
            }
        });

        btSair.setMnemonic('S');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('M');
        jButton1.setText("Mudar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Usuário:");

        tfUsuario.setEditable(false);
        tfUsuario.setFocusable(false);

        jLabel5.setText("Nome:");

        tfNome.setEditable(false);
        tfNome.setFocusable(false);

        lbAlerta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbAlerta.setText("texto de alerta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btGravar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair))
                            .addComponent(tfConfirmacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButton1)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(tfUsuario)
                                        .addComponent(tfNome, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addComponent(lbAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAlerta)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btGravar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String senhaAtual = Seguranca.criptografarSHA256(tfSenhaAtual.getText());

        if (senhaAtual.equals(Sessao.getUsuario().getSenha())) {
            tfNovaSenha.setEnabled(true);
            tfConfirmacao.setEnabled(true);
            tfNovaSenha.requestFocus();
            lbAlerta.setText("Informe a nova senha!");
            lbAlerta.setForeground(Color.BLUE);
            btGravar.setEnabled(true);
        } else {
            lbAlerta.setText("Senha inválida.");
            lbAlerta.setForeground(Color.RED);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfConfirmacaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfConfirmacaoKeyReleased
        if (!tfNovaSenha.getText().equals(tfConfirmacao.getText())) {
            lbAlerta.setText("As senhas não conferem.");
            lbAlerta.setForeground(Color.RED);
        } else {
            lbAlerta.setText("Senhas OK");
            lbAlerta.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_tfConfirmacaoKeyReleased

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if (tfNovaSenha.getText().equals(tfConfirmacao.getText())) {
            Usuario u = Sessao.getUsuario();
            u.setSenha(Seguranca.criptografarSHA256(tfNovaSenha.getText()));
            u.setNovaSenha(false);
            UsuarioDAO udao = DAOFactory.getDefaultDAOFactory().getUsuarioDAO();
            udao.alterar(u);
            initialize();
        } else {
            JOptionPane.showMessageDialog(null, "Verifique as senhas digitadas!");
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void initialize() {
        lbAlerta.setText("");
        tfNovaSenha.setEnabled(false);
        tfConfirmacao.setEnabled(false);
        tfUsuario.setText(Sessao.getUsuario().getNomeUsuario());
        tfNome.setText(Sessao.getUsuario().getNomeCompleto());
        tfSenhaAtual.setText("");
        tfNovaSenha.setText("");
        tfConfirmacao.setText("");
        btGravar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAlerta;
    private javax.swing.JPasswordField tfConfirmacao;
    private javax.swing.JTextField tfNome;
    private javax.swing.JPasswordField tfNovaSenha;
    private javax.swing.JPasswordField tfSenhaAtual;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
