package br.com.ragah.view;

import br.com.ragah.dao.DAOFactory;
import br.com.ragah.dao.model.EmpresaDAO;
import br.com.ragah.util.Sessao;
import br.com.ragah.util.Info;
import br.com.ragah.util.GUIUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author Douglas Gusson
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        lbAcesso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btLogout = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        itemConfiguracoes = new javax.swing.JMenuItem();
        itemMudarSenha = new javax.swing.JMenuItem();
        itemLogout = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ragah");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sessão"));

        lbUsuario.setBackground(new java.awt.Color(204, 204, 204));
        lbUsuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbUsuario.setForeground(java.awt.Color.darkGray);
        lbUsuario.setText("usuario autenticado...");

        lbAcesso.setBackground(new java.awt.Color(250, 250, 250));
        lbAcesso.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbAcesso.setForeground(java.awt.Color.darkGray);
        lbAcesso.setText("inicio da sessão...");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("Início da sessão:");

        lbNome.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lbNome.setForeground(java.awt.Color.darkGray);
        lbNome.setText("nome...");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setText("Nome:");

        btLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/logout_16x16.png"))); // NOI18N
        btLogout.setText("Logout");
        btLogout.setContentAreaFilled(false);
        btLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/sair_16x16.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setContentAreaFilled(false);
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsuario)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAcesso)
                    .addComponent(jLabel2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogout)
                    .addComponent(btSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(852, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(481, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        barraMenu.setOpaque(false);

        menuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/cadastros.png"))); // NOI18N
        menuCadastros.setMnemonic('C');
        menuCadastros.setText("Cadastros");
        menuCadastros.setToolTipText("T");

        jMenuItem3.setMnemonic('F');
        jMenuItem3.setText("Funcionários");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuCadastros.add(jMenuItem3);

        jMenuItem1.setMnemonic('u');
        jMenuItem1.setText("Funções");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCadastros.add(jMenuItem1);

        jMenuItem2.setMnemonic('E');
        jMenuItem2.setText("Estados Civis");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuCadastros.add(jMenuItem2);

        barraMenu.add(menuCadastros);

        menuSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/sistema.png"))); // NOI18N
        menuSistema.setMnemonic('S');
        menuSistema.setText("Sistema");

        jMenuItem4.setMnemonic('e');
        jMenuItem4.setText("Mudar empresa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuItem4);

        itemConfiguracoes.setMnemonic('C');
        itemConfiguracoes.setText("Configurações");
        itemConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfiguracoesActionPerformed(evt);
            }
        });
        menuSistema.add(itemConfiguracoes);

        itemMudarSenha.setMnemonic('M');
        itemMudarSenha.setText("Mudar minha senha");
        itemMudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMudarSenhaActionPerformed(evt);
            }
        });
        menuSistema.add(itemMudarSenha);

        itemLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemLogout.setMnemonic('L');
        itemLogout.setText("Logout");
        itemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLogoutActionPerformed(evt);
            }
        });
        menuSistema.add(itemLogout);

        itemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        itemSair.setMnemonic('S');
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSistema.add(itemSair);

        barraMenu.add(menuSistema);

        menuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/ajuda.png"))); // NOI18N
        menuAjuda.setMnemonic('A');
        menuAjuda.setText("Ajuda");

        itemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ragah/img/info_16x16.png"))); // NOI18N
        itemSobre.setMnemonic('S');
        itemSobre.setText("Sobre");
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemSobre);

        barraMenu.add(menuAjuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfiguracoesActionPerformed
        FrmConfiguracoes configuracoes = new FrmConfiguracoes(this);
        configuracoes.setVisible(true);
    }//GEN-LAST:event_itemConfiguracoesActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        FrmLogin login = new FrmLogin(this);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btLogoutActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        GUIUtils.confirmarSaida(this);
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        GUIUtils.confirmarSaida(this);
    }//GEN-LAST:event_formWindowClosing

    private void itemMudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMudarSenhaActionPerformed
        FrmMudaSenha mudaSenha = new FrmMudaSenha(this);
        mudaSenha.setVisible(true);
    }//GEN-LAST:event_itemMudarSenhaActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        FrmSobre sobre = new FrmSobre(this);
        sobre.setVisible(true);
    }//GEN-LAST:event_itemSobreActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        btSairActionPerformed(evt);
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLogoutActionPerformed
        btLogoutActionPerformed(evt);
    }//GEN-LAST:event_itemLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmFuncoes funcoes = new FrmFuncoes(this);
        funcoes.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmEstadosCivis estadosCivis = new FrmEstadosCivis(this);
        estadosCivis.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmFuncionarios funcionarios = new FrmFuncionarios(this);
        funcionarios.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmBuscaEmpresa buscaEmpresa = new FrmBuscaEmpresa(this);
        buscaEmpresa.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setTitle(Info.getNameMoreVersion()
                + " - " + Sessao.getEmpresa().getRazaoSocial());
    }//GEN-LAST:event_formWindowActivated

    private void initialize() {
        setPermissoes();

        lbUsuario.setText(Sessao.getUsuario().getNomeUsuario());
        lbAcesso.setText(Sessao.acessoToString());
        lbNome.setText(Sessao.getUsuario().getNomeCompleto());

        setDefaultCloseOperation(FrmPrincipal.DO_NOTHING_ON_CLOSE);

        if (Sessao.getUsuario().getNovaSenha()) {
            JOptionPane.showMessageDialog(null, 
                    "Por motivos de segurança, será necessário mudar sua senha.");
            FrmMudaSenha mudaSenha = new FrmMudaSenha(this);
            mudaSenha.setVisible(true);
        }

        EmpresaDAO edao = DAOFactory.getDefaultDAOFactory().getEmpresaDAO();
        if (edao.listarTodas().size() == 1) {
            Sessao.setEmpresa(edao.listarTodas().get(0));
        } else {
            FrmBuscaEmpresa buscaEmpresa = new FrmBuscaEmpresa(this);
            buscaEmpresa.setVisible(true);
        }

        this.setTitle(Info.getNameMoreVersion());

    }

    private void setPermissoes() {
        if (!Sessao.getUsuario().getAdmin()) {
            itemConfiguracoes.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btSair;
    private javax.swing.JMenuItem itemConfiguracoes;
    private javax.swing.JMenuItem itemLogout;
    private javax.swing.JMenuItem itemMudarSenha;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbAcesso;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuSistema;
    // End of variables declaration//GEN-END:variables
}
