package br.com.ragah.view;

import br.com.ragah.dao.DAOFactory;
import br.com.ragah.dao.model.CidadeDAO;
import br.com.ragah.dao.model.EstadoCivilDAO;
import br.com.ragah.dao.model.FuncaoDAO;
import br.com.ragah.dao.model.FuncionarioDAO;
import br.com.ragah.dao.model.TelefoneFuncionarioDAO;
import br.com.ragah.domain.Cidade;
import br.com.ragah.domain.EstadoCivil;
import br.com.ragah.domain.Funcao;
import br.com.ragah.domain.Funcionario;
import br.com.ragah.domain.TelefoneFuncionario;
import br.com.ragah.table.model.TelefoneFuncionarioTableModel;
import br.com.ragah.util.GenericException;
import br.com.ragah.util.Sessao;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Window;
import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Douglas Gusson
 */
public class FrmRegistroFuncionario extends javax.swing.JDialog {

    private static FrmRegistroFuncionario INSTANCIA;

    private static final int OPCAO_INSERIR = 0;
    private static final int OPCAO_ALTERAR = 1;

    private int opcao;
    private List<Funcionario> listaFuncionarios = new ArrayList<>();
    ;
    private int indexRegistro;
    private Funcionario funcionario;
    private Cidade cidade;
    private List<TelefoneFuncionario> listaTelefones = new ArrayList<>();

    Border borderRed = BorderFactory.createLineBorder(Color.red);
    Border borderDefault = BorderFactory.createLineBorder(Color.gray);

    private Vector<EstadoCivil> ecs;
    private DefaultComboBoxModel<EstadoCivil> modeloComboBoxEstadoCivil;

    private Vector<Funcao> funcoes;
    private DefaultComboBoxModel<Funcao> modeloComboBoxFuncao;

    public FrmRegistroFuncionario(Window parent) {
        super(parent, DEFAULT_MODALITY_TYPE);
        INSTANCIA = this;
        initComponents();
        initialize();
    }

    public FrmRegistroFuncionario(Window parent, List<Funcionario> lista) {
        this(parent);
        this.listaFuncionarios = lista;
        this.indexRegistro = -1;
        this.opcao = OPCAO_INSERIR;
    }

    public FrmRegistroFuncionario(Window parent, List<Funcionario> lista, int indice) {
        this(parent, lista);
        if (indice >= 0 && indice < lista.size()) {
            this.indexRegistro = indice;
            this.opcao = OPCAO_ALTERAR;
            this.funcionario = lista.get(indexRegistro);
            this.listaTelefones = this.funcionario.getTelefonesFuncionario();
            tfMatricula.setText(String.valueOf(funcionario.getMatricula()));
        }
    }

    private void initialize() {
        this.tfMatricula.setText(null);
        this.tfMatricula.requestFocus();
        this.tfMatricula.setBorder(borderDefault);
        getRootPane().setDefaultButton(btGravar);
        atualizarCBEstadoCivil();
        atualizarCBFuncao();
        atualizarTabelaTelefones();
    }

    private void atualizarCBEstadoCivil() {

        EstadoCivilDAO estadoCivilDAO = DAOFactory.getDefaultDAOFactory().getEstadoCivilDAO();
        ecs = new Vector<>(estadoCivilDAO.listarTodos());

        modeloComboBoxEstadoCivil = new DefaultComboBoxModel<>(ecs);
        cbEstadoCivil.setModel(modeloComboBoxEstadoCivil);
    }

    private void atualizarCBFuncao() {

        FuncaoDAO funcaoDAO = DAOFactory.getDefaultDAOFactory().getFuncaoDAO();
        funcoes = new Vector<>(funcaoDAO.listarTodos());

        modeloComboBoxFuncao = new DefaultComboBoxModel<>(funcoes);
        cbFuncao.setModel(modeloComboBoxFuncao);

    }

    private void atualizarTabelaTelefones() {
        tbTelefones.setModel(new TelefoneFuncionarioTableModel(this.listaTelefones));
        //tbTelefones.setDefaultRenderer(Object.class, new TelefoneFuncionarioCellRenderer());
        ((AbstractTableModel) tbTelefones.getModel()).fireTableDataChanged();
    }

    public static FrmRegistroFuncionario getInstancia() {
        return INSTANCIA;
    }

    public void setCidade(Cidade c) {
        cidade = c;
        tfCidade.setText(cidade.getNome());
        tfUf.setText(cidade.getUf().getSigla());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        tfRg = new javax.swing.JTextField();
        tfCtps = new javax.swing.JTextField();
        tfSalario = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        tfUf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTelefones = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        tfNumeroTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfDescricaoTelefone = new javax.swing.JTextField();
        brAddTelefone = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        cbEstadoCivil = new javax.swing.JComboBox();
        cbFuncao = new javax.swing.JComboBox();
        dcDataNacimento = new com.toedter.calendar.JDateChooser();
        dcDataAdmissao = new com.toedter.calendar.JDateChooser();
        dcDataDemissao = new com.toedter.calendar.JDateChooser();
        btNovoEstadoCivil = new javax.swing.JButton();
        btNovaFuncao = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Funcionáro");

        jLabel1.setText("Matrícula:");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("RG:");

        jLabel5.setText("CTPS:");

        jLabel6.setText("Data Nasc.:");

        jLabel7.setText("Estado Civil:");

        jLabel8.setText("Salário:");

        jLabel9.setText("Data Admissão:");

        jLabel10.setText("Data Demissão:");

        jLabel11.setText("Função:");

        jLabel12.setText("Endereço:");

        jLabel13.setText("CEP:");

        jLabel14.setText("Bairro:");

        jLabel15.setText("Cidade:");

        jLabel16.setText("Telefones:");

        jLabel17.setText("UF:");

        tfCidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCidadeFocusLost(evt);
            }
        });

        tfUf.setEditable(false);
        tfUf.setBackground(new java.awt.Color(255, 255, 255));
        tfUf.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbTelefones);

        jLabel18.setText("Nº Telefone:");

        jLabel19.setText("Descrição:");

        brAddTelefone.setText("ADD");
        brAddTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brAddTelefoneActionPerformed(evt);
            }
        });

        btGravar.setMnemonic('G');
        btGravar.setText("Gravar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        btSair.setMnemonic('S');
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btNovoEstadoCivil.setText("...");
        btNovoEstadoCivil.setToolTipText("Cadastrar novo estado civil");
        btNovoEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoEstadoCivilActionPerformed(evt);
            }
        });

        btNovaFuncao.setText("...");
        btNovaFuncao.setToolTipText("Cadastrar nova função");
        btNovaFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovaFuncaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNome))
                            .addComponent(tfEndereco)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBairro))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel17))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfNumeroTelefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfDescricaoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(brAddTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfUf)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfCtps)
                                    .addComponent(tfCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(dcDataNacimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btNovoEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfRg))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btNovaFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dcDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dcDataDemissao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(cbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNovoEstadoCivil))
                    .addComponent(dcDataNacimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(dcDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(dcDataDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovaFuncao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(tfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNumeroTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(tfDescricaoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(brAddTelefone)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair)
                    .addComponent(btGravar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed

        if (tfMatricula.getText().trim().equals("")) {
            tfMatricula.setBorder(borderRed);
            tfMatricula.requestFocus();
        } else if (tfNome.getText().trim().equals("")) {
            tfNome.setBorder(borderRed);
            tfNome.requestFocus();
        } else if (tfCpf.getText().trim().equals("")) {
            tfCpf.setBorder(borderRed);
            tfCpf.requestFocus();
        } else if (dcDataNacimento.getCalendar() == null){
            JOptionPane.showMessageDialog(null, "A data de nascimento deve ser informada.");
        } else if ((cbEstadoCivil.getItemAt(cbEstadoCivil.getSelectedIndex())) == null) { 
            cbEstadoCivil.setBorder(borderRed);
            cbEstadoCivil.requestFocus();
        } else {
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

            FuncionarioDAO fdao = DAOFactory.getDefaultDAOFactory().getFuncionarioDAO();
            TelefoneFuncionarioDAO tfdao = DAOFactory.getDefaultDAOFactory().getTelefoneFuncionarioDAO();

            switch (opcao) {

                case OPCAO_INSERIR:

                    Funcionario f = new Funcionario();
                    Instant instant;
                    LocalDateTime dateTime;

                    f.setMatricula(Integer.parseInt(tfMatricula.getText()));
                    f.setNome(tfNome.getText());
                    f.setCpf(tfCpf.getText());
                    f.setRg(tfRg.getText());
                    f.setCtps(tfCtps.getText());

                    try {
                        instant = dcDataNacimento.getCalendar().toInstant();
                        dateTime = LocalDateTime.ofInstant(instant, ZoneId.systemDefault());
                        LocalDate dataNascimento = dateTime.toLocalDate();
                        f.setDataNascimento(dataNascimento);
                    } catch (Exception e) {
                        throw new GenericException("Falha ao tentar converter a data", e);
                    }

                    EstadoCivil ec = (EstadoCivil) cbEstadoCivil.getItemAt(cbEstadoCivil.getSelectedIndex());
                    f.setEstadoCivil(ec);

                    f.setSalario(new BigDecimal(tfSalario.getText().replace(",", ".")));

                    try {
                        instant = dcDataAdmissao.getCalendar().toInstant();
                        dateTime = LocalDateTime.ofInstant(instant, ZoneId.systemDefault());
                        LocalDate dataAdmissao = dateTime.toLocalDate();
                        f.setDataAdmissao(dataAdmissao);
                    } catch (Exception e) {
                        throw new GenericException("Falha ao tentar converter a data", e);
                    }

                    if (dcDataDemissao.getCalendar() != null) {
                        try {
                            instant = dcDataDemissao.getCalendar().toInstant();
                            dateTime = LocalDateTime.ofInstant(instant, ZoneId.systemDefault());
                            LocalDate dataDemissao = dateTime.toLocalDate();
                            f.setDataDemissao(dataDemissao);
                        } catch (Exception e) {
                            throw new GenericException("Falha ao tentar converter a data", e);
                        }
                    } else {
                        f.setDataDemissao(null);
                    }

                    Funcao funcao = (Funcao) cbFuncao.getItemAt(cbFuncao.getSelectedIndex());
                    f.setFuncao(funcao);

                    f.setEndereco(tfEndereco.getText());
                    f.setCep(tfCep.getText());
                    f.setBairro(tfBairro.getText());

                    f.setCidade(cidade);
                    f.setEmpresa(Sessao.getEmpresa());
                    f.setTelefonesFuncionario(listaTelefones);

                    f.setCriacao(LocalDateTime.now());
                    f.setAlteracao(LocalDateTime.now());

                    fdao.inserir(f);

                    for (int i = 0; i < listaTelefones.size(); i++) {
                        listaTelefones.get(i).setFuncionario(f);
                        tfdao.inserir(listaTelefones.get(i));
                    }

                    System.out.println(f.toString());

                    break;

                case OPCAO_ALTERAR:

                    break;

            }

            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }

    }//GEN-LAST:event_btGravarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void brAddTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brAddTelefoneActionPerformed

        if ((this.tfNumeroTelefone.getText().trim()).equals("")) {
            this.tfNumeroTelefone.setBorder(borderRed);
            this.tfNumeroTelefone.requestFocus();
        } else {

            TelefoneFuncionario tf = new TelefoneFuncionario();

            tf.setNumTelefone(tfNumeroTelefone.getText());
            tf.setDescricao(tfDescricaoTelefone.getText());

            tfNumeroTelefone.setText(null);
            tfDescricaoTelefone.setText(null);

            listaTelefones.add(tf);

            atualizarTabelaTelefones();
        }

    }//GEN-LAST:event_brAddTelefoneActionPerformed

    private void tfCidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCidadeFocusLost

        String query = tfCidade.getText().trim();

        if (!query.equals("")) {

            CidadeDAO cdao = DAOFactory.getDefaultDAOFactory().getCidadeDAO();

            List<Cidade> cidades = cdao.buscarPorNome(query);

            if (cidades.isEmpty()) {
                tfCidade.setText(null);
            } else if (cidades.size() == 1) {
                setCidade(cidades.get(0));
            } else {
                tfCidade.setText(null);
                FrmBuscaCidade buscaCidade = new FrmBuscaCidade(this, cidades);
                buscaCidade.setVisible(true);
            }
        }

    }//GEN-LAST:event_tfCidadeFocusLost

    private void btNovaFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovaFuncaoActionPerformed
        FrmFuncoes frmFuncoes = new FrmFuncoes(this);
        frmFuncoes.setVisible(true);
        atualizarCBFuncao();
    }//GEN-LAST:event_btNovaFuncaoActionPerformed

    private void btNovoEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoEstadoCivilActionPerformed
        FrmEstadosCivis frmEstadosCivis = new FrmEstadosCivis(this);
        frmEstadosCivis.setVisible(true);
        atualizarCBEstadoCivil();
    }//GEN-LAST:event_btNovoEstadoCivilActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brAddTelefone;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btNovaFuncao;
    private javax.swing.JButton btNovoEstadoCivil;
    private javax.swing.JButton btSair;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JComboBox cbFuncao;
    private com.toedter.calendar.JDateChooser dcDataAdmissao;
    private com.toedter.calendar.JDateChooser dcDataDemissao;
    private com.toedter.calendar.JDateChooser dcDataNacimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbTelefones;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JTextField tfCtps;
    private javax.swing.JTextField tfDescricaoTelefone;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumeroTelefone;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JTextField tfUf;
    // End of variables declaration//GEN-END:variables
}
